apiVersion: v1
kind: Service
metadata:
  name: memcache-service
  namespace: prod
  labels:
    name: mem
    author: Tawfeeq
spec:
  type: ClusterIP
  ports:
    - targetPort: mem-port
      port: 80
      protocol: TCP
  selector:
    app: mem-dep
