apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: prod
  labels:
    app: app-dep
    author: Tawfeeq
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: app-dep
  template:
    metadata:
      labels:
        app: app-dep
    spec:
      containers:
        - name: app
          image: tawfeeq421/java-app
          ports:
            - name: app-port
              containerPort: 8080
          resources:
            requests:
              cpu: 150
              memory: 120Mi
            limits:
              cpu: 250m
              memory: 240Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5


