apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: prod
  labels:
    name: db
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: db-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-state
  namespace: prod
  labels:
    name: db-app
    author: Tawfeeq
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
       containers:
         - name: mysql-db
           image: mysql:8.0.33
           ports:
             - containerPort: 3306
           env:
             - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: db-secret
                   key: MYSQL_ROOT_PASSWORD
             - name: MYSQL_DATABASE:
               valueFrom:
                 secretKeyRef:
                   name: db-secret
                   key: MYSQL_DATABASE
           volumeMounts:
             - name: mysql-volume
               mountPath: /var/lib/mysql
    volumeClaimTemplates:
      - metadata:
          name: mysql-volume
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

      


      


