apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
  namespace: prod
  labels:
    app: rabbit
    author: Tawfeeq
spec:
  type: ClusterIp
  ports:
    - targetPort: rab-port
      port: 80
      procotol: TCP

  selector:
    app: rab-dep
